title: Vagrant + Ansible

description: |

  How we used Vagrant plus Ansible to provision our project from development out to production.

baseurl: "/RubyMN-Vagrant-Ansible-2016-06-27"

markdown: kramdown
reveal:
  theme: moon
  codetheme: zenburn

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .sass-cache
